{
 "title": "Docker",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "label_values(docker_container_running_state, instance)"
    }
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": {
     "query": "label_values(docker_container_running_state{instance =~ \"$instances\"}, name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(increase(docker_container_cpu_used_total{instance =~ \"$instances\", name =~ \"$containers\"}[30s]) / increase(docker_container_cpu_capacity_total[30s])) > 0 or (increase(docker_container_cpu_used_total{instance =~ \"$instances\", name =~ \"$containers\"}[1m]) / increase(docker_container_cpu_capacity_total[1m])) > 0 or (increase(docker_container_cpu_used_total{instance =~ \"$instances\", name =~ \"$containers\"}[3m]) / increase(docker_container_cpu_capacity_total[3m])) > 0 or (increase(docker_container_cpu_used_total{instance =~ \"$instances\", name =~ \"$containers\"}[5m]) / increase(docker_container_cpu_capacity_total[5m]))",
     "legendFormat": "{{instance}} / {{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_memory_used_bytes{instance =~ \"$instances\", name=~ \"$containers\"}",
     "legendFormat": "{{instance}} / {{name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "time() - docker_container_start_time_seconds{instance =~ \"$instances\", name =~ \"$containers\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(docker_container_running_state{instance =~ \"$instances\", name =~ \"$containers\"}) without (__name__)"
    },
    {
     "expr": "sum(increase(docker_container_restart_count{instance =~ \"$instances\", name =~ \"$containers\"}[$__range])) without (__name__)"
    }
   ]
  },
  {
   "title": "Network I/O (+in, -out)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-rate(docker_container_network_in_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[$__rate_interval])",
     "legendFormat": "{{instance}} / {{name}} in"
    },
    {
     "expr": "rate(docker_container_network_out_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[$__rate_interval])",
     "legendFormat": "{{instance}} / {{name}} out"
    },
    { "expr": "vector(0)", "legendFormat": "Zero point reference" }
   ]
  },
  {
   "title": "Disk I/O (+write, -read)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-rate(docker_container_disk_read_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[$__rate_interval])",
     "legendFormat": "{{instance}} / {{name}} read"
    },
    {
     "expr": "rate(docker_container_disk_write_bytes{instance =~ \"$instances\", name =~ \"$containers\"}[$__rate_interval])",
     "legendFormat": "{{instance}} / {{name}} write"
    },
    { "expr": "vector(0)", "legendFormat": "Zero point reference" }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Volume sizes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_volume_size{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} / {{name}}"
    }
   ]
  },
  {
   "title": "Number of containers using a volume",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "docker_volume_container_count{instance=~\"$instances\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Image sizes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_image_size{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} / {{tag}}"
    }
   ]
  },
  {
   "title": "Number of containers using an image",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "docker_image_container_count{instance=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}